### ISSUE TITLE
Task: Create mockups

### ISSUE THREAD

**Issue by DevPhilB** [conclurer/midnightboard#106]
**What needs to be done?**

Mockups for
- [x] notice board design
- [x] notice board interaction (e.g. create note, add PDF, move element)
- [x] user login
Optional:
- [x] user profile & settings
- [x] CMS (user configuration as Super-User)

**When is this task complete?**

All mockups are created

**Additional Notes**

Tools could be: https://app.moqups.com/

To be finalized
Due date: 11.12.

**Comment by DevPhilB** [comment]
Evaluate exisiting examples for design notice board.

**Comment by DevPhilB** [comment]
https://app.moqups.com/vtLzbRhz6s/view

**Comment by MistereoSC** [comment]
https://imgur.com/a/5GQpRmm

**Comment by eddifab** [comment]
User Login: https://imgur.com/a/jhi0W5S
CMS: https://imgur.com/a/juFk4dK

**Comment by DevPhilB** [comment]
TODO: Create mockups in Moqups from images

**Comment by eddifab** [comment]
Updated Mockups:
Midnightboard: https://app.moqups.com/vtLzbRhz6s/view/page/ab74c1c29
CMS: https://app.moqups.com/gg0alPnVyL/view/page/ad64222d5
