### ISSUE TITLE
Task: Setup project

### ISSUE THREAD

**Issue by Simon-Deuring** [conclurer/midnightboard#108]
**What needs to be done?**
- [x] Setup frontend
- [x] Setup backend
- [x] Setup Docker
- [x] Setup CI/CD and Testing Enviroment
- [x] Create demo from Use case
- [x] Setup Danger JS

**When is this task complete?**
When all tasks are finished and runnable example is ready

**Additional Notes**
Docker, CI/CD and Testing are connected to each other

For scrum development
Due date: 18.12. (extended till 06.01.)

**Comment by DevPhilB** [comment]
Like: https://github.com/DevPhilB/sails-vue-test-circle

**Comment by DevPhilB** [comment]
Danger JS: 
https://danger.systems/js/
Bot: https://github.com/MidnightboardDangerJS
