### ISSUE TITLE
Task: Evaluate requirements 

### ISSUE THREAD

**Issue by wasdJens** [conclurer/midnightboard#12]
**What needs to be done?**

As the development team you should evaluate the first set of requirements the customer has and 
* Ask about missing information
* Create possible user stories out of it
* Get an idea / basic understanding of the product.
* Add your own possible ideas for the product

After finishing this task you (the development team) should be able to 
* create the first concepts for our software (Technical, design etc)
* define the architecture for our software (Possible APIs, Database tables etc)
* create a set of milestones that you think when the software reaches a certain point during development

**When is this task complete?**

**Additional Notes**

* Product is looking at the finish software from the customers point of view. (for example) as the customer I dont care what database is used in the background 
* Software is more for the technical aspects of our finished product

Should be done with all members of this project

**Comment by TanaroSchaedler** [comment]
**Questions in the Meeting on 06.11.2019:**
- Multi-Language Support for the midnightboard?
- Specific Design requirements?

**Comment by Simon-Deuring** [comment]
**Answers:**

 -  Multi-Language Support for the midnightboard?
    -> Englisch/German (implement extendable)
 -  Specific Design requirements?
    -> Free but user-oriented design
 -  Static User System or option to integrate existing LDAP?
    -> User system is a must-have element. External solutions can be used.

**Comment by wasdJens** [comment]
I updated the existing requirements with more information. I also added the full document inside our slack channel.

Would closing this in favour of new issues or if some requirements are unclear just comment under the requirement issue. 

next step would be to create issues / planning based on the requirements.
