### ISSUE TITLE
Task: Define code guidelines 

### ISSUE THREAD

**Issue by wasdJens** [conclurer/midnightboard#13]
**What needs to be done?**

As the development team you should come up with some guidelines on how to 
* Review (How to review a pull request?)
* Contribute (Creating pull requests)
* etc.

**When is this task complete?**

- [x] When there is a template for pull requests 

- [x] The [conventions](https://github.com/conclurer/midnightboard/blob/master/CONVENTIONS.md) document is updated with new information
 
**Additional Notes**

There are already some existing guidelines to the repo found inside under conventions in the root folder. 

For scrum development
Due date: 11.12.

**Comment by wasdJens** [comment]
No milestone for this one yet - maybe during the concept phase.

**Comment by wasdJens** [comment]
Added this to the next milestone

**Comment by DevPhilB** [comment]
The pull request template is currently located inside the development branch (until our first PR).
