### ISSUE TITLE
As a company I want to have a digital notice board 

### ISSUE THREAD

**Issue by eddifab** [conclurer/midnightboard#161]
**Description:** 
As a company I want to have a digital notice board to display different content.

Acceptance criteria:

- [x] Branding is shown
- [x] "Board options" button
- [x] "Profile Settings" button
- [x] "Add note" button
- [x] "Add file" button
- [x] Notice boards must have a masonry layout

Test case (web browser):

- [x] Open the vue project on localhost and check if everything is displayed correctly.

**Comment by Simon-Deuring** [comment]
Questions: 
- [ ] Why is a "Delete board" button needed on the board?
- [ ] "Create new board" button makes more sense in "My Boards" view

**Comment by Simon-Deuring** [comment]
![Board1](https://user-images.githubusercontent.com/33379546/72671329-c4adc400-3a48-11ea-90bd-acfa07b3a388.png)

@wasdJens Please evaluate the overall design of the notice board.
