### ISSUE TITLE
As a user I want to display text notes on a notice board

### ISSUE THREAD

**Issue by DevPhilB** [conclurer/midnightboard#17]
**Description:**

The user interface is able to show all notes belonging to a notice board. Notes can have different types and tags. By default they are visible, but they also can be set invisible (also see #51, #52). They can be moved on the notice board and they also can be scaled. These settings shall be saved for each note.

**Acceptance criteria:**
- [x] Notes are displayed
- [x] Notes are auto-scaled

**Test case (Web browser):**
- [x] Create a new text note, switch to another user and check if note is displayed correctly on the notice board

**Comment by Simon-Deuring** [comment]
Dependent on: #33 (As a user I want to post text notes on a notice board)

**Comment by Simon-Deuring** [comment]
![Board2](https://user-images.githubusercontent.com/33379546/72671338-ea3acd80-3a48-11ea-968a-14c15d3013dd.png)

@wasdJens Please evaluate the new design of the notice board and the text note design.
(The note with the orange border is highlighted because the mouse pointer is on in)
