### ISSUE TITLE
An independent developer can authenticate their application using OAuth 2.0

### ISSUE THREAD

**Issue by MistereoSC** [conclurer/midnightboard#173]
**Acceptance criteria:**
- [ ] Developers can authenticate their application using an OAuth token.
- [ ] When authentication is successful, a JWT is supplied to the application.

**Test case (Independent Test Application):**
- [ ] Authenticate an independent application using an OAuth token, and check if the authentication was successful.

**Comment by wasdJens** [comment]
Closing this in favor of other "core" features (e.g. more custom content etc) instead of oauth stuff.
