### ISSUE TITLE
As a creator, I want to delete my own notice boards

### ISSUE THREAD

**Issue by MistereoSC** [conclurer/midnightboard#175]
**Description:**

When a board is not used anymore, there is no need to keep it in the database. In this case, the creator of the board can delete it. Deleted boards are not visible any more for users and also cannot be accessed.

**Acceptance Criteria:**
- [x] Creators should be able to delete his own boards
- [x] Admins can delete all boards
- [x] Deleted boards are inaccessible to all users

**Test case(Web browser):**
- [x] Create a new board, add another user to it and delete it. Then check if the board is still listed in the "All boards" view. Check if the deleted notice board is accessible in any way.

**Comment by Simon-Deuring** [comment]
Only admins (Super-Users) can delete notice boards due to the new permission system.
