### ISSUE TITLE
Users receive a JWT upon login

### ISSUE THREAD

**Issue by MistereoSC** [conclurer/midnightboard#177]
**Acceptance criteria:**
- [x] User's receive a JWT upon login
- [x] JWT expires automatically after 1 hour

**Test case (test tool):**
- [x] When logging in, check if a JWT was receivec
- [x] While logged in , check if the JWT correctly expires after the expiration timer. The expiration time may be changed to a lower value for this test's purpopses only.

**Comment by wasdJens** [comment]
> JWT expires when a user logs in on a different device

From user experience standpoint this design choice would lead to many emails why they always need to log in again when they use different devices. In most cases the jwt will be stored inside the browsers localstorage you should just check if they are expired but let users login from multiple devices. (Compare with other websites you are not logged out when you use mobile apps / browser apps)
