### ISSUE TITLE
As a user I want to display PDF files on a notice board

### ISSUE THREAD

**Issue by DevPhilB** [conclurer/midnightboard#18]
**Description:**

The user interface is able to show all notes belonging to a notice board. Notes can have different types and tags. By default they are visible, but they also can be set invisible (also see #51, #52). They can be moved on the notice board and they also can be scaled. These settings shall be saved for each note.
PDFs are displayed as a download link.

**Acceptance criteria:**
- [x] PDF are displayed in a preview
- [x] PDF is displayed as a download link
- [x] PDF can be downloaded

**Test case (Web browser):**
- [x] Upload a PDF file, switch to another user and check if PDF file is displayed correctly on the notice board

**Comment by Simon-Deuring** [comment]
First page displayed on preview ?

**Comment by Simon-Deuring** [comment]
Idea was rejected. Maybe possible at the end of the project.

**Comment by Simon-Deuring** [comment]
> First page displayed on preview ?

Idea was rejected. Maybe possible at the end of the project.

**Comment by DevPhilB** [comment]
> 
> Idea was rejected. Maybe possible at the end of the project.

Please update the acceptance criteria according to our new requirements.
> 
> PDFs are displayed as a download link.
