### ISSUE TITLE
Feedback Milestone 2 

### ISSUE THREAD

**Issue by wasdJens** [conclurer/midnightboard#223]
Please create create corresponding issues for these problems or discuss with me if they are not "real" problems. If everything here is documented you can close this issue. For better references below I am using a bullet point list. Please note that the ordering has nothing to do with how critical something is or something is not. 

# Feedback Milestone 2

1. Please update the language picker. At the moment it is shown the language that I can switch to from my current language but it would be more clear if I see my current selected language so that I know which language I am using. 

![Screenshot 2020-03-09 at 12 38 12](https://user-images.githubusercontent.com/24612796/76210143-cb181b00-6203-11ea-9891-a6d6fc35842d.png)

2. When working on the language picker please also think about a possible solution to better indicate the user that he can switch his languages by clicking on the button? At the moment users may not know how they can change their language 

3. There are translations missing when switching to german. See following screenshot 

![Screenshot 2020-03-09 at 12 40 04](https://user-images.githubusercontent.com/24612796/76210318-2ba75800-6204-11ea-8e92-1ba4752bfa8c.png)

4. As a user it is not quite clear were the "input" box is located. Suggestion from me - Maybe add a border around the input so that is more clear what is the input field. The same could be applied to the title. 

![Screenshot 2020-03-09 at 12 41 02](https://user-images.githubusercontent.com/24612796/76210369-4a0d5380-6204-11ea-9ee8-44e86db1b2d0.png)

5. At the moment I can no longer create normal posts on my board. I am getting a 500 server error. I followed the setup described in [quick setup](https://github.com/conclurer/midnightboard#quick-setup-with-docker) 

![Screen Recording 2020-03-09 at 12 50 21 mov](https://user-images.githubusercontent.com/24612796/76210697-ed5e6880-6204-11ea-816d-15b7fafe2758.gif)

![Screenshot 2020-03-09 at 12 51 43](https://user-images.githubusercontent.com/24612796/76210708-f18a8600-6204-11ea-810a-e52bc00ffedb.png)

6. Are images / posts split from each other? Because right now I have an extra option when selecting an image. Can I also combine my image with a normal post or a images / posts split? 

![Screenshot 2020-03-09 at 12 54 24](https://user-images.githubusercontent.com/24612796/76210799-2696d880-6205-11ea-9cac-928b74097b39.png)

7. Removing an image does not reset my image title 

![Screen Recording 2020-03-09 at 12 55 37 mov](https://user-images.githubusercontent.com/24612796/76211011-96a55e80-6205-11ea-9608-5fa8b6a1f642.gif)

8. You should remove console logging in prod builds. If you still want to log things for better debug purposes you can use a vue logging plugin (or write one yourself by following this [guide](https://riptutorial.com/vue-js/example/27220/simple-logger) ) and disable it in prod builds.

![Screenshot 2020-03-09 at 12 57 45](https://user-images.githubusercontent.com/24612796/76211023-9e650300-6205-11ea-91fa-1e02dd0e8211.png)

9. Missing translations for upload buttons

![Screenshot 2020-03-09 at 12 58 18](https://user-images.githubusercontent.com/24612796/76211063-ad4bb580-6205-11ea-8347-37a7f58de953.png)

**Comment by Simon-Deuring** [comment]
Ad 4)
This issue was addressed and fixed yesterday. The following style is now merged into branch 'development'.

![grafik](https://user-images.githubusercontent.com/33379546/76221318-33252c00-6219-11ea-9ea8-886c7028772c.png)

**Comment by Simon-Deuring** [comment]
Ad 5)
I have also followed the instructions described in quick setup and it worked without any 500 server errors:

![1](https://user-images.githubusercontent.com/33379546/76227680-f7419500-621f-11ea-9c22-b2b387f9354e.png)

![3](https://user-images.githubusercontent.com/33379546/76227701-fc064900-621f-11ea-8a02-ce9f7f2c76f1.png)

**Comment by wasdJens** [comment]
See alos my most recent slack message today @Simon-Deuring @DevPhilB @MistereoSC
