### ISSUE TITLE
As a user I want to have different editors for each content type

### ISSUE THREAD

**Issue by Simon-Deuring** [conclurer/midnightboard#227]
**Description:**

When the right sidebar is opened not all editors shall be displayed in one container. The user can select which type of post he wants to create. Afterwards the matching editor is displayed in the right sidebar.

**Acceptance criteria:**

- [x] Dropdown elements for:
- Text notes
- Images
- Files
- Polls
- Surveys
- [x] Each element activates the right sidebar with the matching editor
- [x] Move datepickers to EditorSidebars

**Test case (Web browser):**
- [x] Click on each dropdown element and check whether it is opening the corresponding editor

**Additional notes:**

#223 Aspect 6

**Comment by wasdJens** [comment]
Maybe also think about a possible idea like a quick create options for users that mainly use one option? 

Or allow the user to set one option afterwards as his default option something like that.

**Comment by DevPhilB** [comment]
Handed over to @Simon-Deuring
