### ISSUE TITLE
As a company I want a default board for all users

### ISSUE THREAD

**Issue by DevPhilB** [conclurer/midnightboard#24]
**Description:**

The administrator of the system can set a default notice board. This board is called the global board. It is visible and accessable for all users of the system.

**Acceptance criteria:**
- [x] Default board is accessible for each user
- [x] Any user can see the contents on the default board

**Test case (Web browser):**
- [x] Change to Content Management System, set a default board, log in as another user and check if default board is loaded and visible

**Additional notes:**

See also issue #23

**Comment by Simon-Deuring** [comment]
Only registered users?

**Comment by MistereoSC** [comment]
Who can post on default boards ? Possibly 2 different boards; one that everyone can post to, and one that only certain users can post important announcements ?
