### ISSUE TITLE
Bug: You can vote multiple times as the same user 

### ISSUE THREAD

**Issue by wasdJens** [conclurer/midnightboard#253]
**Describe the bug**
* You can cast multiple votes in the same poll as the same user.
* When refreshing the page you can vote again in a poll. 

**To Reproduce**
Create a poll. 
Vote once.
Use the browser to refresh the page. 
Repeat

![Screen Recording 2020-03-31 at 11 59 14 mov](https://user-images.githubusercontent.com/24612796/78013993-94877900-7347-11ea-87df-b0c620c4330c.gif)

**Expected behavior**
To not mess up poll results users should only be allowed to vote once in a poll. After voting you should store the voted users id in the server.

**Screenshots**

**Additional context**

**Comment by DevPhilB** [comment]
Fix in PR #260 doesn't include any additional UI feedback, he can still click on the vote button but his vote doesn't count (is refused by the server).

**Comment by wasdJens** [comment]
> he can still click on the vote button but his vote doesn't count (is refused by the server).

If possible direclty show the result page if the user has already voted
