### ISSUE TITLE
Bug: Surveys wrong behavior on deleting fields

### ISSUE THREAD

**Issue by MistereoSC** [conclurer/midnightboard#262]
**Describe the bug**
- When deleting **any** answer within a Multiple-Choice-Field, the last field is always deleted instead of the selected 
- When deleting an input field, most other fields are cleared, or their text end up within the wrong field 

**To Reproduce**
1. Open the Note Editor, and scroll to the survey section.
2. Click on 'single/multiple choice(s)'
3. Enter multiple answers
4. Delete any, but the last answer
---
1. Open the Note Editor, and scroll to the survey section.
2. Enter some values in all survey fields.
3. Delete any input field

**Expected behavior**
Only the selected field / answer should be deleted. No other fields should be cleared

**Screenshots**
![Bug-1](https://user-images.githubusercontent.com/56682008/78241503-c54ee600-74e0-11ea-8fdc-7647bc7599da.gif)

---
---

![Bug-2](https://user-images.githubusercontent.com/56682008/78241513-ca139a00-74e0-11ea-9386-7ea344624083.gif)

**Comment by DevPhilB** [comment]
This bug is on a feature branch and not on master or development!
I have informed @MistereoSC about our PR review process and bug reporting.
