### ISSUE TITLE
As a user I want to get a notification for new announcements

### ISSUE THREAD

**Issue by DevPhilB** [conclurer/midnightboard#31]
**Description:**

Users may want to be notified when something is posted on a notice board. They can subscribe a board and get notifications for new content. Of course, they can also unsubscribe notice boards. If a board is set hidden for a user, he/she won't get any notifications from this notice board.

**Acceptance criteria:**
- [x] Notice boards can be subscribed
- [x] Notice boards can be unsubscribed
- [x] Users who have subscribed a notice board are informed about new posts
- [x] Users don't get notifications from the default board

**Test case (Web browser):**
- [x] Subscribe to a notice board, create a new note and check mail account for notification mail
- [x] Unsubscribe to a notice board, create a new note and check mail account for notification mails, no mail should have been sent
- [x] Hide a notice board, create a new note and check mail account for notification mails, no mail should have been sent

**Additional notes:**

Notifications e.g. via e-mail or via sound signal
See also issue #25

**Comment by DevPhilB** [comment]
https://www.npmjs.com/package/nodemailer 📧 
That package looks really interesting (MIT license & zero dependencies).

**Comment by wasdJens** [comment]
> https://www.npmjs.com/package/nodemailer 📧

We are using the same package at conclurer
