### ISSUE TITLE
As a Super-User I want to remove content from my board 

### ISSUE THREAD

**Issue by eddifab** [conclurer/midnightboard#52]
**Description:** 

Super-Users can remove content from notice boards. These post will be deleted from the database directly.

**Acceptance criteria:**

- [x] "Delete" button for each board element (content)
- [x] This button delete the content from this board and from the database
- [x] Deleted content is no longer visible/accessible (for all users)

**Test case (Web browser):**

- [x] Create a new board/open a board as a Super-User, delete some content, switch to another user who have access and check if its no longer visible respectively deleted
- [x] Also check in the database if the content is deleted

**Comment by Simon-Deuring** [comment]
Archive mechanic?
