### ISSUE TITLE
Task: (Learning) VueJs and its ecosystem

### ISSUE THREAD

**Issue by wasdJens** [conclurer/midnightboard#7]
**What needs to be done?**

For our frontend application we want to use [VueJs](https://vuejs.org/). Since no one of our team has any real vue experience we want to try it out and learn the basics of it. 

* Read the offical vue documentation and get an idea of the framework and what it does.
* Build your own first vue application (You can use the (vue cli) [https://cli.vuejs.org/] for this 
   * If you want you can push your source code to a different branch on this repo
* Create your own simple vue website to learn the basics of vue.
* Describe in text the concepts of vue and maybe try to differentiate it from other frontend frameworks (e.g. react or angular)

Beside the offical documentation the following "tools" should also be explored:
* For state management take a look at (vuex)[https://vuex.vuejs.org/] 
   * What is it?
   * Why is it useful?
* For routing take a look at (vue router)[https://router.vuejs.org/]
* For multiple language support (required in #6) (vue-i18n)[https://kazupon.github.io/vue-i18n/]
(vue cli) [https://cli.vuejs.org/]
* How to use bootstrap in vue https://bootstrap-vue.js.org/ (Or maybe also explore other open source plugins for design etc.) 

**When is this task complete?**

- [x] When you have a basic understanding of vue and its ecosystem

- [x] You understand the basic concepts of vue (hint component based)

- [x] You can showcase a small vue application to your teammates 

**Additional Notes**

In our other learnings we are still kinda open to different frameworks / solutions but for the frontend part vuejs is "set in stone". 

@ Tanaro 

@ Simon

**Comment by wasdJens** [comment]
Updated with more information.

**Comment by wasdJens** [comment]
@Simon-Deuring You can also add your notes under this issue that you showed today in the meeting. (Your pdf)

**Comment by Simon-Deuring** [comment]
[Vue.pdf](https://github.com/conclurer/midnightboard/files/3846002/Vue.pdf)
