### ISSUE TITLE
As a user I want to change my user data

### ISSUE THREAD

**Issue by eddifab** [conclurer/midnightboard#74]
**Description:**
User data (such as username or e-mail address) may change over time. It shall be possible for the users to configure them. Users are also able to change their passwords. This makes the application safe from fraud.

**Acceptance criteria:**
- [x] Users can change their username in their profile settings.
_Second point was moved to_ #58 / #154
- [x] Users can change their e-mail address in their profile settings.
- [x] Users can change their password in their profile settings.

**Test cases:**
- [x] Create a new user. Change username, e-mail and password in the profile settings
- [x] Log out, and back in, and check if the new password applied
- [x] Go to the profile page and check if the correct username, avatar and e-mail is displayed

**Comment by eddifab** [comment]
E-Mail, Avatar, Username, Password, Displayname

**Comment by MistereoSC** [comment]
Should Displayname be the users real name ?

**Comment by DevPhilB** [comment]
> 
> 
> Should Displayname be the users real name ?

We talk about a business environment, so in general, yes!
But with the requirement of having a displayname we should give the user the option to change it.
