### ISSUE TITLE
Task: (Learning) Continous Integration and the devops cycle

### ISSUE THREAD

**Issue by wasdJens** [conclurer/midnightboard#8]
**What needs to be done?**

For this project we want to use continous integration (and other stuff of the dev ops cycle). The goal is to setup a devops pipeline for this project which automates tasks for us so that we can focus on development etc.

For example each pull request to a master branch ( or dev branch) should always trigger a build pipeline, a test pipeline and maybe other automated tasks. 
* The changed files should still result in a successfull build - we dont want to waste a reviwers time by building the project locally. 
* Tests should always run when adding new features / reworking features etc. To ensure that new changes dont break existing features.
* To enforce our pull requests guideline we could also take a look at (danger ci)[https://danger.systems/js/] e.g. that each pull request has an assignee or that when changing files a changelog is provided 

We also want to provide automatic deployment for our software so that we dont need to run a local build to use it or if we want to test different production builds (e.g. A prod build and a dev build)
To later "sell" the software or provide different companies access different docker images could be build to provide the software.

**When is this task complete?**

- [x] Explore the dev ops world

- [x] Try maybe out different tools to achieve our goals

- [x] Setup a concept on how our devops cycle could look like for this project. 

- [x] Add your own ideas!

**Additional Notes**

Since we have not yet decided on a tooling you can also play around with different providers of devops services and maybe discuss in the team presentation why you would choose the following service over an other service.

https://www.docker.com/ 
https://circleci.com/

@DevPhilB

**Comment by wasdJens** [comment]
Updated with some more information about the task.

**Comment by DevPhilB** [comment]
Concept: https://github.com/DevPhilB/sails-vue-test-circle
