### ISSUE TITLE
As a user I want to create polls on a notice board

### ISSUE THREAD

**Issue by DevPhilB** [conclurer/midnightboard#81]
**Description:**

Users can post interactive content. Polls are an example for this. They can consist of radio buttons, regular buttons, check boxes and text fields. Users can configure new polls in a design area and post them to a notice board.

**Subtasks:**
- [x] #197 
- [x] #198

**Comment by Simon-Deuring** [comment]
@wasdJens What is the exact difference between polls and surveys?

**Comment by wasdJens** [comment]
Poll => Abstimmung
Survey => Umfrage

**Comment by Simon-Deuring** [comment]
Thanks for the fast answer. Does it mean that polls have predefined answers to pick and surveys have more free answer possibilities?

In implementation they are largely the same.

**Comment by DevPhilB** [comment]
@Simon-Deuring https://crowdsignal.com/support/difference-between-a-poll-and-a-survey/

**Comment by wasdJens** [comment]
> Does it mean that polls have predefined answers to pick and surveys have more free answer possibilities?

Poll => Quantitativ (Auswahlmöglichkeit)
Survey => Frage mit qualitativer antwort (Meistens freie Antwort auch auf die Frage)

**Comment by Simon-Deuring** [comment]
Thank you for the answers.
